# Generated by Django 5.2.4 on 2025-09-08 12:39

from django.db import migrations

def create_groups(apps, schema_editor):
    """
    Cria os grupos de usuários 'Zeladoria' e 'Solicitante de Serviços' no banco de dados.
    """
    Group = apps.get_model('auth', 'Group')

    groups_to_create = ['Zeladoria', 'Solicitante de Serviços']

    for group_name in groups_to_create:
        # get_or_create evita a criação duplicada se o grupo já existir
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_groups),
    ]