# Generated by Django 5.2.4 on 2025-09-14 18:16

from django.db import migrations

def renomear_grupo(apps, schema_editor):
    """
    Renomeia o grupo 'Corpo Docente' para 'Solicitante de Serviços'.
    """
    Group = apps.get_model('auth', 'Group')
    try:
        grupo = Group.objects.get(name='Corpo Docente')
        grupo.name = 'Solicitante de Serviços'
        grupo.save()
    except Group.DoesNotExist:
        # Se o grupo antigo não existir, não faz nada.
        # Isso garante que a migração possa ser executada em novos bancos de dados.
        pass

def reverter_renomeacao(apps, schema_editor):
    """
    Função para reverter a migração, caso necessário.
    """
    Group = apps.get_model('auth', 'Group')
    try:
        grupo = Group.objects.get(name='Solicitante de Serviços')
        grupo.name = 'Corpo Docente'
        grupo.save()
    except Group.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_groups'),
    ]

    operations = [
        migrations.RunPython(renomear_grupo, reverse_code=reverter_renomeacao),
    ]
