# Generated by Django 5.2.4 on 2025-07-09 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_numero",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome/Número"
                    ),
                ),
                ("capacidade", models.IntegerField(verbose_name="Capacidade")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "localizacao",
                    models.CharField(max_length=100, verbose_name="Localização"),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
                "ordering": ["nome_numero"],
            },
        ),
        migrations.CreateModel(
            name="LimpezaRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora_limpeza",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data e Hora da Limpeza"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "funcionario_responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Funcionário Responsável",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_limpeza",
                        to="salas.sala",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Limpeza",
                "verbose_name_plural": "Registros de Limpeza",
                "ordering": ["-data_hora_limpeza"],
            },
        ),
    ]
