# Generated by Django 5.2.4 on 2025-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
