# Generated by Django 5.2.4 on 2025-09-10 12:02

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Sala = apps.get_model('salas', 'Sala')
    for row in Sala.objects.all():
        row.qr_code_id = uuid.uuid4()
        row.save(update_fields=['qr_code_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_sala_ativa'),
    ]

    operations = [
        # 1. Adiciona o campo, mas permitindo que ele seja nulo por enquanto
        migrations.AddField(
            model_name='sala',
            name='qr_code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='ID para QR Code'),
        ),
        # 2. Roda nosso código Python para preencher cada linha com um UUID único
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),

        # 3. Altera o campo para torná-lo único e não-nulo
        migrations.AlterField(
            model_name='sala',
            name='qr_code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID para QR Code'),
        ),
    ]