# Generated by Django 5.2.4 on 2025-09-10 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_populate_sala_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='qr_code_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='ID para QR Code'),
        ),
    ]
