# Generated by Django 5.2.4 on 2025-09-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_alter_sala_qr_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='instrucoes',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções de Limpeza'),
        ),
    ]
