# Generated by Django 5.2.4 on 2025-09-10 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0005_sala_instrucoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='capacidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='A capacidade deve ser de no mínimo 1.'), django.core.validators.MaxValueValidator(2000, message='A capacidade máxima não pode exceder 2000.')], verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
