# Generated by Django 5.2.4 on 2025-09-10 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0006_alter_sala_capacidade_alter_sala_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Zeladoria'}, related_name='salas_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis pela Limpeza'),
        ),
    ]
