# Generated by Django 5.2.4 on 2025-09-10 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0007_sala_responsaveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='validade_limpeza_horas',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1, message='A validade da limpeza deve ser de no mínimo 1 hora.')], verbose_name='Validade da Limpeza (em horas)'),
        ),
    ]
