# Generated by Django 5.2.4 on 2025-09-12 13:09

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0008_sala_validade_limpeza_horas'),
    ]

    operations = []
