# Generated by Django 5.2.4 on 2025-09-14 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salas", "0009_generate_initial_pdf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="limpezaregistro",
            options={
                "ordering": ["-data_hora_inicio"],
                "verbose_name": "Registro de Limpeza",
                "verbose_name_plural": "Registros de Limpeza",
            },
        ),
        migrations.RemoveField(
            model_name="limpezaregistro",
            name="data_hora_limpeza",
        ),
        migrations.AddField(
            model_name="limpezaregistro",
            name="data_hora_fim",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fim da Limpeza"
            ),
        ),
        migrations.AddField(
            model_name="limpezaregistro",
            name="data_hora_inicio",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 14, 2, 27, 43, 218228, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Início da Limpeza",
            ),
            preserve_default=False,
        ),
    ]
