# Generated by Django 5.2.4 on 2025-09-14 02:28

from datetime import timedelta
from django.db import migrations

def popular_data_inicio(apps, schema_editor):
    """
    Define um horário de início para os registros de limpeza existentes.

    Para cada registro que já foi concluído (possui data_hora_fim),
    esta função define a data_hora_inicio como 15 minutos antes da
    data de conclusão, para manter a consistência dos dados.
    """
    LimpezaRegistro = apps.get_model('salas', 'LimpezaRegistro')
    registros_antigos = LimpezaRegistro.objects.filter(data_hora_inicio__isnull=True, data_hora_fim__isnull=False)

    for registro in registros_antigos:
        registro.data_hora_inicio = registro.data_hora_fim - timedelta(minutes=15)
        registro.save(update_fields=['data_hora_inicio'])

class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0010_alter_limpezaregistro_options_and_more'),
    ]

    operations = [
        migrations.RunPython(popular_data_inicio),
    ]