# Generated by Django 5.2.4 on 2025-09-14 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salas", "0011_popular_inicio_limpeza"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioSalaSuja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data e Hora do Relatório"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "reportado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reportado por",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorios_suja",
                        to="salas.sala",
                        verbose_name="Sala Reportada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Sala Suja",
                "verbose_name_plural": "Relatórios de Sala Suja",
                "ordering": ["-data_hora"],
            },
        ),
    ]
