# Generated by Django 5.2.4 on 2025-09-14 19:05

import salas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salas", "0012_relatoriosalasuja"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=salas.models.sala_image_path,
                verbose_name="Imagem da Sala",
            ),
        ),
    ]
