# Generated by Django 5.2.4 on 2025-09-14 21:35

import django.db.models.deletion
import salas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salas", "0013_sala_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoLimpeza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to=salas.models.foto_limpeza_path)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "registro_limpeza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="salas.limpezaregistro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de Limpeza",
                "verbose_name_plural": "Fotos de Limpeza",
                "ordering": ["timestamp"],
            },
        ),
    ]
