# Generated by Django 5.2.4 on 2025-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0014_fotolimpeza'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='data_notificacao_pendencia',
            field=models.DateTimeField(blank=True, help_text='Registra quando a última notificação de limpeza pendente foi enviada.', null=True, verbose_name='Data da Última Notificação de Pendência'),
        ),
    ]
