# Generated by Django 5.2.4 on 2025-10-18 05:28

from django.db import migrations

def create_initial_pdf(apps, schema_editor):
    """
    Função que será executada pela migração para gerar o PDF inicial.
    Importamos a função de geração de PDF aqui dentro para garantir que
    todas as aplicações já estejam carregadas quando ela for chamada,
    e que o schema do banco de dados já inclua todos os campos necessários.
    """
    try:
        # Importa a função aqui para garantir acesso ao estado atual do código
        from salas.pdf_generator import generate_salas_pdf
        print("\nGerando PDF inicial com as salas existentes...")
        generate_salas_pdf()
        print("PDF inicial gerado com sucesso.")
    except Exception as e:
        print(f"\nOcorreu um erro ao gerar o PDF inicial: {e}")
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0015_sala_data_notificacao_pendencia'),
    ]

    operations = [
        migrations.RunPython(create_initial_pdf, reverse_code=migrations.RunPython.noop),
    ]
