# Generated by Django 5.2.4 on 2025-09-08 11:47

from django.db import migrations

def create_missing_profiles(apps, schema_editor):
    """
    Cria um objeto Profile para cada User que ainda não tenha um.
    """
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')

    # Filtra apenas os usuários que não têm um perfil associado
    users_without_profiles = User.objects.filter(profile__isnull=True)

    # Cria um perfil para cada um deles
    for user in users_without_profiles:
        Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'), # Altere para o nome da sua migração anterior que criou o modelo Profile
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]